---
- name: Load a variable file based on the OS type
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: If nfs-server is present
  include_tasks: nfs-server.yml
  when: nfs_enable.server | bool or ('nfs_enable' in item and item.nfs_enable.server | bool)
  loop: "{{ nfs_configurations }}"

- name: If nfs-clients is present
  include_tasks: nfs-clients.yml
  when: nfs_enable.clients | bool or ('nfs_enable' in item and item.nfs_enable.clients | bool)
  loop: "{{ nfs_configurations }}"
